include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle nice_view_adapter dongle_display_view_seeeduino_xiao_ble
  - board: seeeduino_xiao_ble
    shield: settings_reset
